apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/restartedAt: "2026-07-11T17:46:37+05:30"
  creationTimestamp: "2026-07-12T08:09:15Z"
  generateName: observability-6d7c98cdd6-
  generation: 1
  labels:
    app: replenix-observability
    pod-template-hash: 6d7c98cdd6
    topology.kubernetes.io/region: blr1
  name: observability-6d7c98cdd6-2qrkn
  namespace: replenix-prod
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: observability-6d7c98cdd6
    uid: b0cc603b-95f2-499a-803a-4c25a1d7c370
  resourceVersion: "16219881"
  uid: d7a26ee0-bca2-4be6-a0c8-b5b0d5206f6b
spec:
  containers:
  - env:
    - name: PORT
      value: "3001"
    - name: NODE_ENV
      value: production
    - name: ADMIN_USER
      value: admin
    - name: ADMIN_PASS
      valueFrom:
        secretKeyRef:
          key: ADMIN_PASS
          name: replenix-secrets
          optional: true
    envFrom:
    - secretRef:
        name: replenix-secrets
    image: sujaynsv/replenix-observability:e77229e0ddc766933b9983b85b05cb9282de8bd4
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /healthz
        port: 3001
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 5
    name: observability
    ports:
    - containerPort: 3001
      protocol: TCP
    readinessProbe:
      failureThreshold: 5
      httpGet:
        path: /healthz
        port: 3001
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-g4qrl
      readOnly: true
  dnsConfig:
    nameservers:
    - 10.122.32.10
    options:
    - name: ndots
      value: "4"
    searches:
    - svc.cluster.local
    - cluster.local
  dnsPolicy: None
  enableServiceLinks: true
  nodeName: replenix-pool-3u49xv
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: observability-sa
  serviceAccountName: observability-sa
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-g4qrl
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  allocatedResources:
    cpu: 100m
    memory: 256Mi
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-07-12T08:09:52Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-07-12T08:09:51Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-07-12T08:10:30Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-07-12T08:10:30Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-07-12T08:09:51Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: 100m
      memory: 256Mi
    containerID: containerd://dfc69e68a230ff3174d5f1d470131ecc3080812f65a48cc921019d6b2eadc5eb
    image: docker.io/sujaynsv/replenix-observability:e77229e0ddc766933b9983b85b05cb9282de8bd4
    imageID: docker.io/sujaynsv/replenix-observability@sha256:a93526858b96a4fcd6b9258b70bb6f8fb58b39b881ee1d369c6b64323e0e9fa2
    lastState: {}
    name: observability
    ready: true
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-07-12T08:10:20Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 0
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-g4qrl
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.122.0.4
  hostIPs:
  - ip: 10.122.0.4
  observedGeneration: 1
  phase: Running
  podIP: 10.123.0.163
  podIPs:
  - ip: 10.123.0.163
  qosClass: Burstable
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 79m
      memory: 256Mi
  startTime: "2026-07-12T08:09:51Z"
