apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app: replenix-redis
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: replenix-redis
  template:
    metadata:
      labels:
        app: replenix-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
