"""Add advanced training parameters to TrainingRun

Revision ID: 815259f84a29
Revises: 002
Create Date: 2026-06-16 00:14:02.388765
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '815259f84a29'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('start_day', sa.Integer(), nullable=True),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('overrides', sa.JSON(), nullable=True),
    sa.Column('initial_inventory', sa.Integer(), nullable=False),
    sa.Column('max_order', sa.Integer(), nullable=False),
    sa.Column('action_step', sa.Integer(), nullable=False),
    sa.Column('holding_cost', sa.Float(), nullable=True),
    sa.Column('stockout_penalty', sa.Float(), nullable=True),
    sa.Column('final_rl_reward', sa.Float(), nullable=True),
    sa.Column('final_human_reward', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['training_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_results_id'), 'evaluation_results', ['id'], unique=False)
    op.add_column('training_runs', sa.Column('gamma', sa.Float(), nullable=True))
    op.add_column('training_runs', sa.Column('learning_rate', sa.Float(), nullable=True))
    op.add_column('training_runs', sa.Column('sweep_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_training_runs_id'), 'training_runs', ['id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_id'), 'uploaded_files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_files_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_training_runs_id'), table_name='training_runs')
    op.drop_column('training_runs', 'sweep_id')
    op.drop_column('training_runs', 'learning_rate')
    op.drop_column('training_runs', 'gamma')
    op.drop_index(op.f('ix_evaluation_results_id'), table_name='evaluation_results')
    op.drop_table('deployment_sessions')
    # ### end Alembic commands ###
