global:
  security:
    allowInsecureImages: true

image:
  registry: quay.io
  repository: thanos/thanos
  tag: v0.35.1

existingObjstoreSecret: thanos-objstore-secret
existingObjstoreSecretItems:
  - key: thanos.yaml
    path: objstore.yml

query:
  enabled: true
  replicaCount: 1
  replicaLabel: replica
  dnsDiscovery:
    sidecarsService: prometheus-operated
    sidecarsNamespace: monitoring
  stores:
    - dnssrv+_grpc._tcp.thanos-storegateway.monitoring.svc.cluster.local
  extraFlags:
    - --query.auto-downsampling
    - --query.partial-response
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

storegateway:
  enabled: true
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: do-block-storage
    size: 20Gi
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

compactor:
  enabled: true
  # Retention per downsampling resolution
  retentionResolutionRaw: 30d    # 15s raw data — 30 days
  retentionResolution5m: 180d    # 5m downsampled — 6 months
  retentionResolution1h: 730d    # 1h downsampled  — 2 years
  persistence:
    enabled: true
    storageClass: do-block-storage
    size: 20Gi
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"

ruler:
  enabled: false   # Using Prometheus-embedded rules instead
